sudo: required
services:
    - docker

script:
    - docker build -t dini/node .
    - docker images dini/node

before_deploy:
    - docker login -u dinirichard -p Solo1992.


deploy:
    provider: script
    script: bash docker_push.sh
    on: 
        branch: master
