sudo: required
services:
    - docker

script:
    - docker build -t dinirichard/node .
    - docker images dinirichard/node

before_deploy:
    - docker login -u dinirichard -p Solo1992.


deploy:
    skip_cleanup: true
    provider: script
    script: bash docker_push.sh
    on: 
        branch: master
